/**
 * Production migration runner.
 *
 * Reads migrations/ (generated by `drizzle-kit generate`) and applies any
 * that haven't been run yet, tracked via the `drizzle.__drizzle_migrations`
 * table. Safe to run on every deploy — it's a no-op if the schema is
 * already up-to-date.
 *
 * Usage:
 *   npm run db:migrate
 *
 * Why this exists (instead of `db:push`):
 *   `drizzle-kit push` diffs the schema file against the live DB and
 *   emits destructive DDL for renames (drop column, add column). It also
 *   prompts interactively on destructive diffs, which hangs or silently
 *   fails in a non-TTY deploy container. `migrate` applies reviewed SQL
 *   files — if a migration would drop data, we see it in the generated
 *   file before it hits prod.
 *
 * Baselining:
 *   Databases that predate migration tracking (built up by `db:push`)
 *   already have every table in 0000_baseline.sql, so running that file
 *   would fail on the first CREATE TABLE. When we detect an existing,
 *   untracked database we record the baseline as applied without running
 *   it, then let the migrator apply everything after it. Fresh databases
 *   (CI, new environments) run the full chain from 0000.
 */

import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { is, sql } from "drizzle-orm";
import { PgTable, getTableConfig } from "drizzle-orm/pg-core";
import pg from "pg";
import * as appSchema from "../shared/schema";

const { Pool } = pg;

const MIGRATIONS_FOLDER = "./migrations";

interface JournalEntry {
  idx: number;
  when: number;
  tag: string;
}

function readJournal(): JournalEntry[] {
  const journal = JSON.parse(
    readFileSync(`${MIGRATIONS_FOLDER}/meta/_journal.json`, "utf8"),
  );
  return journal.entries as JournalEntry[];
}

/** Hash exactly the way drizzle-orm's migrator does: sha256 of the file. */
function hashMigration(tag: string): string {
  const content = readFileSync(`${MIGRATIONS_FOLDER}/${tag}.sql`, "utf8");
  return createHash("sha256").update(content).digest("hex");
}

/**
 * Schema drift check — compares shared/schema.ts against the live database.
 *
 * Baselining trusts that an existing untracked database matches
 * 0000_baseline.sql. When it doesn't (the DB predates columns in the
 * baseline), the difference is never applied and the app crashes at runtime
 * with "column ... does not exist" — this is what caused the June 2026 auth
 * outage and a local dev breakage on the users table. Missing tables or
 * columns fail the migration run loudly instead.
 *
 * Extra tables/columns in the DB that the schema doesn't know about are
 * ignored — they're harmless to the app. Escape hatch: SKIP_DRIFT_CHECK=1.
 */
async function checkSchemaDrift(db: ReturnType<typeof drizzle>): Promise<void> {
  if (process.env.SKIP_DRIFT_CHECK === "1") {
    // eslint-disable-next-line no-console
    console.warn("[migrate] SKIP_DRIFT_CHECK=1 — skipping schema drift check");
    return;
  }

  const live = await db.execute(sql`
    SELECT table_name, column_name
    FROM information_schema.columns
    WHERE table_schema = 'public'
  `);
  const liveColumns = new Set(
    (live.rows as Array<{ table_name: string; column_name: string }>).map(
      (r) => `${r.table_name}.${r.column_name}`,
    ),
  );

  const missing: string[] = [];
  for (const exported of Object.values(appSchema)) {
    if (!is(exported, PgTable)) continue;
    const { name: tableName, columns } = getTableConfig(exported);
    for (const column of columns) {
      if (!liveColumns.has(`${tableName}.${column.name}`)) {
        missing.push(`${tableName}.${column.name}`);
      }
    }
  }

  if (missing.length > 0) {
    // eslint-disable-next-line no-console
    console.error(
      `[migrate] SCHEMA DRIFT: the database is missing ${missing.length} column(s) the app expects:\n` +
        missing.map((m) => `  - ${m}`).join("\n") +
        `\nThe app would crash at runtime on these. Generate a migration for the difference\n` +
        `(npx drizzle-kit generate --name <description>) or, for local dev only, run\n` +
        `"npm run db:push" then "npm run db:migrate" to re-sync.`,
    );
    process.exit(1);
  }
  // eslint-disable-next-line no-console
  console.log("[migrate] schema drift check passed — database matches shared/schema.ts");
}

async function main() {
  if (!process.env.DATABASE_URL) {
    // eslint-disable-next-line no-console
    console.error("DATABASE_URL is not set — cannot run migrations.");
    process.exit(1);
  }

  const pool = new Pool({
    connectionString: process.env.DATABASE_URL,
    // Short connection timeout — migrations run at boot, and we'd rather
    // fail the deploy than hang the container waiting for a dead DB.
    connectionTimeoutMillis: 10_000,
    max: 1,
  });

  const db = drizzle(pool);

  try {
    const [baseline] = readJournal();
    if (!baseline) throw new Error("migrations/meta/_journal.json has no entries");

    await db.execute(sql`CREATE SCHEMA IF NOT EXISTS drizzle`);
    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS drizzle.__drizzle_migrations (
        id SERIAL PRIMARY KEY,
        hash TEXT NOT NULL,
        created_at BIGINT
      )
    `);

    // The migrator applies every journal entry whose `when` is newer than
    // the last recorded created_at, so "is the baseline tracked" reduces to
    // a timestamp comparison.
    const tracked = await db.execute(sql`
      SELECT MAX(created_at)::bigint AS latest FROM drizzle.__drizzle_migrations
    `);
    const latest = Number((tracked.rows[0] as any)?.latest || 0);

    if (latest < baseline.when) {
      const existing = await db.execute(sql`SELECT to_regclass('public.users') AS t`);
      const hasAppTables = Boolean((existing.rows[0] as any)?.t);

      if (hasAppTables) {
        // eslint-disable-next-line no-console
        console.log(
          `[migrate] existing untracked database detected — recording ${baseline.tag} as applied (baselining)`,
        );
        await db.execute(sql`
          INSERT INTO drizzle.__drizzle_migrations (hash, created_at)
          VALUES (${hashMigration(baseline.tag)}, ${baseline.when})
        `);
      }
    }

    // eslint-disable-next-line no-console
    console.log("[migrate] applying migrations from ./migrations ...");
    await migrate(db, { migrationsFolder: MIGRATIONS_FOLDER });
    await checkSchemaDrift(db);
    // eslint-disable-next-line no-console
    console.log("[migrate] complete");
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error("[migrate] FAILED:", err);
    process.exit(1);
  } finally {
    await pool.end();
  }
}

main();
