/**
 * Production migration runner.
 *
 * Reads migrations/ (generated by `drizzle-kit generate`) and applies any
 * that haven't been run yet, tracked via the `drizzle.__drizzle_migrations`
 * table. Safe to run on every deploy — it's a no-op if the schema is
 * already up-to-date.
 *
 * Usage:
 *   npm run db:migrate
 *
 * Why this exists (instead of continuing to use `db:push`):
 *   `drizzle-kit push` diffs the schema file against the live DB and
 *   emits destructive DDL for renames (drop column, add column). That's
 *   fine in dev where we nuke and repave, but on a deploy it can lose
 *   data without warning. `migrate` applies reviewed SQL files — if a
 *   migration would drop data, we see it in the generated file before
 *   it hits prod.
 *
 * NOTE — the `migrations/` folder currently has a journal mismatch
 * (journal lists 0000 only, but 0001_add_check_constraints.sql and
 * 0001_event_log_immutability_trigger.sql both exist on disk). That
 * needs to be reconciled before switching the Dockerfile CMD to run
 * this script. Until then, the Dockerfile still runs `db:push` on
 * startup and this script is a no-op opt-in for local testing.
 */

import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import pg from "pg";

const { Pool } = pg;

async function main() {
  if (!process.env.DATABASE_URL) {
    // eslint-disable-next-line no-console
    console.error("DATABASE_URL is not set — cannot run migrations.");
    process.exit(1);
  }

  const pool = new Pool({
    connectionString: process.env.DATABASE_URL,
    // Short connection timeout — migrations run at boot, and we'd rather
    // fail the deploy than hang the container waiting for a dead DB.
    connectionTimeoutMillis: 10_000,
    max: 1,
  });

  const db = drizzle(pool);

  try {
    // eslint-disable-next-line no-console
    console.log("[migrate] applying migrations from ./migrations ...");
    await migrate(db, { migrationsFolder: "./migrations" });
    // eslint-disable-next-line no-console
    console.log("[migrate] complete");
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error("[migrate] FAILED:", err);
    process.exit(1);
  } finally {
    await pool.end();
  }
}

main();
